= Spring Cloud for Cloud Foundry

include::intro.adoc[]

== Quickstart

include::quickstart.adoc[]

== How Does it Work?

=== OAuth2 Single Sign On

Spring Cloud Security provides the `@EnableOAuth2Sso` annotation and
binds the app to environment properties in `oauth2.\*`. Spring Cloud
for Cloud Foundry just sets up default environment properties so that
it all just works if you bind to a Cloud Foundry service instance
called "sso". The service credentials are mapped to the SSO
properties, i.e. (from `oauth2.client.\*`) `clientId`, `clientSecret`,
`tokenUri`, `authorizationUri`, (and from `oauth2.resource.\*`)
`userInfoUri`, `tokenInfoUri`, `keyValue`, `keyUri`. Refer to the
Spring Cloud Security documentation for details of which combinations
will work together. The main thing is that in Cloud Foundry you only
need one service to cover all the necessary credentials.

To use a different sercice instance name (i.e. not "sso") just set
`oauth2.sso.serviceId` to your custom name.

=== JWT Tokens

Spring Cloud Security already has support for decoding JWT tokens if
you just provide the verification key (as an environment property). In
Cloud Foundry you can pick that property up from a servcice binding
(`keyValue` or `keyUri`).

For example the `keyUri` in PWS is
"https://uaa.run.pivotal.io/token_key":

----
$ curl https://uaa.run.pivotal.io/token_key
{"alg":"SHA256withRSA","value":"-----BEGIN PUBLIC KEY-----\nMIIBI...\n-----END PUBLIC KEY-----\n"}d
----

=== OAuth2 Resource Server

Similarly, the `@EnableOAuth2Resource` annotation will protect your
API endpoints if you bind to a service instance called "resource".
The "sso" service above will work for a resource server as well (so
just bind to that if it's there). If the OAuth2 tokens are JWTs (as in
Cloud Foundry), it is common to use a separate service for resources
to avoid a network round trip decoding the token on every access. A
user-provided-service for an OAuth2 resource can be created like this
on PWS:

----
$ cf create-user-provided-service resource -p '{keyUri:"https://uaa.run.pivotal.io/token_key"}
----

To use JWT you need to add the verification key as either
`keyValue` or `keyUri` (these could be added to the "sso"
service or the "resource" service if you have one).

To use a different sercice instance name (i.e. not "resource" or
"sso") just set `oauth2.resource.serviceId` to your custom name.

=== Default Environment Keys

The precise mapppings are as follows:

* `oauth2.sso.\*` to `vcap.services.${oauth2.sso.serviceId:sso}.credentials.*`

* `oauth2.client.\*` to `vcap.services.${oauth2.sso.serviceId:sso}.credentials.tokenUri:${vcap.services.${oauth2.resource.serviceId:resource}.credentials.*`

* `oauth2.resource.(jwt).\*` to `vcap.services.${oauth2.resource.serviceId:resource}.credentials.tokenUri:${vcap.services.${oauth2.sso.serviceId:sso}.credentials.*`


