= Spring Cloud for Cloud Foundry
:nofooter:

include::intro.adoc[]

The first time you use it the discovery client might be slow owing to
the fact that it has to get an access token from Cloud Foundry.

== Discovery

include::quickstart.adoc[]

The `DiscoveryClient` can lists all the apps in a space, according to
the credentials it is authenticated with, where the space defaults to
the one the client is running in (if any). If neither org nor space
are configured, they default per the user's profile in Cloud Foundry.

== Single Sign On

NOTE: All of the OAuth2 SSO and resource server features moved to Spring Boot
in version 1.3. You can find documentation in the
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/[Spring Boot user guide].

This project provides automatic binding from CloudFoundry service
credentials to the Spring Boot features. If you have a CloudFoundry
service called "sso", for instance, with credentials containing
"client_id", "client_secret" and "auth_domain", it will bind
automatically to the Spring OAuth2 client that you enable with
`@EnableOAuth2Sso` (from Spring Boot). The name of the service can be
parameterized using `spring.oauth2.sso.serviceId`.
